"""remove client model

Revision ID: 30fc4178ab3f
Revises: b98cfee55e5e
Create Date: 2026-07-20 23:14:24.543073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fc4178ab3f'
down_revision = 'b98cfee55e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Reordered: the FK must be dropped before the table it references, not after.
    with op.batch_alter_table('motor_assets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('motor_assets_client_id_fkey'), type_='foreignkey')
        batch_op.drop_column('client_id')

    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motor_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('motor_assets_client_id_fkey'), 'clients', ['client_id'], ['id'])

    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('clients_pkey'))
    )
    # ### end Alembic commands ###
