"""add is_admin to users

Revision ID: 85c07972b87e
Revises: 30fc4178ab3f
Create Date: 2026-07-21 00:48:25.455239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c07972b87e'
down_revision = '30fc4178ab3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows to false; NOT NULL would otherwise fail
    # against a populated table. Dropped again below once the column is in place.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.alter_column('is_admin', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
