"""initial schema

Revision ID: 9feb36960a9d
Revises: 
Create Date: 2026-07-20 16:24:55.559691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9feb36960a9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('motor_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['motor_assets.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'metric', 'timestamp')
    )
    # ### end Alembic commands ###

    # Convert sensor_readings into a TimescaleDB hypertable partitioned on `timestamp`.
    # Runs in a SAVEPOINT so a Postgres server without the timescaledb extension
    # (e.g. local dev without Timescale installed) still gets a working plain table
    # instead of failing the whole migration.
    bind = op.get_bind()
    savepoint = bind.begin_nested()
    try:
        bind.execute(sa.text("CREATE EXTENSION IF NOT EXISTS timescaledb"))
        bind.execute(
            sa.text(
                "SELECT create_hypertable('sensor_readings', 'timestamp', "
                "if_not_exists => TRUE, migrate_data => TRUE)"
            )
        )
        savepoint.commit()
    except Exception as exc:
        savepoint.rollback()
        print(
            f"timescaledb extension not available ({exc}); "
            "sensor_readings left as a plain table."
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_readings')
    op.drop_table('motor_assets')
    op.drop_table('users')
    op.drop_table('clients')
    # ### end Alembic commands ###
